### ISSUE TITLE
[PSXPC_N] "out of texture space error" crash

### ISSUE THREAD

**Issue by Wuups** [TOMB5/TOMB5#235] opened 2020-02-25 17:59 UTC
Reproduce as in the video:
https://youtu.be/t3K3q6SWFQU

Camera has to be on the slope facing Lara for the crash to happen.
![image](https://user-images.githubusercontent.com/38836940/75273342-4f12e180-57c6-11ea-9e12-1e4004902820.png)

**Comment by Gh0stBlade** [comment] 2020-02-29 14:42
Looks to be caused by a temporary assertion i put in place to debug an existing error. Should be resolved soon.

**Comment by Gh0stBlade** [comment] 2020-03-19 14:48
Can you try latest code and see if this is fixed? Looks like it could be a Lara drawing issue.

**Comment by XProger** [comment] 2020-04-02 14:18
should be fixed

**Comment by Gh0stBlade** [comment] 2020-04-03 00:28
I already fixed this by room rendering function split.

**Closed by Gh0stBlade** 2020-04-03 00:28 UTC
Labels: [Bug], [Crash], [Critical], [Enhancement], [M2], [PSXPC]
